# Generated by Django 5.0 on 2024-02-01 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionTracker', '0003_auto_20231219_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontype',
            name='admission_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtype',
            name='blood_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='medical_condition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AdmissionTracker.bloodtype'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AdmissionTracker.gender'),
        ),
        migrations.AlterField(
            model_name='patientmedicationlink',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmissionTracker.medication'),
        ),
        migrations.AlterField(
            model_name='patientmedicationlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmissionTracker.patient'),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
